# Generated by Django 5.0.7 on 2024-08-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_watchlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
